version: '3.8'

services:
  # E-commerce Frontend
  ecom-frontend:
    build: .
    container_name: ecom-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "4202:4202"
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4202/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ecom-network:
    driver: bridge 